
name: test-action

on:
  workflow_dispatch:
    inputs:
      skip_check_run:
        required: false
      gist_name:
        required: false
  #push:
  #release:
  #  types: published

jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v1
      
      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100-preview.7.20366.6'

      - name: use this action, default args (missing solution/project paths)
        ## We expect this one to fail
        continue-on-error: true
        id: testAction1
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      ## This one does not work as expected because
      ## VSTest logs all projects in a solution to
      ## the same output file, overwriting the TRX
      ## each time, so only the last one wins!
      ##   https://github.com/microsoft/vstest/issues/2113
      ##   https://github.com/microsoft/vstest/issues/880
      - name: use this action, test solution dir
        if: ${{ !cancelled() }}
        id: testAction2
        uses: ./
        with:
          project_path: tests
          report_name: tests_0_all_in_solution
          report_title: All Tests In Solution -- Last Project Wins!
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: use this action, xunit project dir
        if: ${{ !cancelled() }}
        id: testAction3a
        uses: ./
        with:
          project_path: tests/samples.xunit/AssertExamples
          report_name: tests_1_xunit
          report_title: Sample XUnit Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: dotnet-tests-report_xunit.md
          gist_badge_label: 'XUnit Tests: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}

      - name: use this action, nunit project dir
        if: ${{ !cancelled() }}  
        id: testAction3b
        uses: ./
        with:
          project_path: tests/nunit-csharp-samples/syntax
          report_name: tests_2_nunit
          report_title: Sample NUnit Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: dotnet-tests-report_nunit.md
          gist_badge_label: 'NUnit Tests: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}

      - name: use this action, mstest project dir
        if: ${{ !cancelled() }}  
        id: testAction3c
        uses: ./
        with:
          project_path: tests/rafaelfgx_DotNetTests/MSTest
          report_name: tests_3_mstest
          report_title: Sample MSTest Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: dotnet-tests-report_mstest.md
          gist_badge_label: 'MSTest Tests: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}

  ## For testing out tests on Windows
  run-tests-on-win:
    if: ${{ false }}
    runs-on: windows-latest
    continue-on-error: true
    steps:

      - name: checkout
        uses: actions/checkout@v1
      
      - name: use this action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
